import fs from 'node:fs';
import path from 'node:path';
import type { EnvFile } from './types.js';

export function loadEnv(rootDir: string): EnvFile {
  const filePath = path.join(rootDir, '.env');
  const values: Record<string, string> = {};

  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, 'utf-8');
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIndex = trimmed.indexOf('=');
      if (eqIndex === -1) continue;
      const key = trimmed.slice(0, eqIndex).trim();
      let value = trimmed.slice(eqIndex + 1).trim();
      // Strip surrounding quotes
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      values[key] = value;
    }
  }

  return { values, filePath };
}

export function saveEnv(env: EnvFile): void {
  const lines: string[] = [
    '# Open Brain configuration',
    '# Generated by openbrain setup',
    '',
    '# Supabase',
    `SUPABASE_URL=${env.values['SUPABASE_URL'] ?? ''}`,
    `SUPABASE_SERVICE_ROLE_KEY=${env.values['SUPABASE_SERVICE_ROLE_KEY'] ?? ''}`,
    '',
    '# LLM Providers',
    `OPENAI_API_KEY=${env.values['OPENAI_API_KEY'] ?? ''}`,
    `ANTHROPIC_API_KEY=${env.values['ANTHROPIC_API_KEY'] ?? ''}`,
    '',
    '# Embedding',
    `EMBEDDING_MODEL=${env.values['EMBEDDING_MODEL'] ?? 'text-embedding-3-small'}`,
    '',
    '# Secrets',
    `CAPTURE_WEBHOOK_SECRET=${env.values['CAPTURE_WEBHOOK_SECRET'] ?? ''}`,
    `CAPTURE_JWT_SECRET=${env.values['CAPTURE_JWT_SECRET'] ?? ''}`,
    `MCP_CLIENT_SECRET=${env.values['MCP_CLIENT_SECRET'] ?? ''}`,
    '',
  ];

  fs.writeFileSync(env.filePath, lines.join('\n'));
  fs.chmodSync(env.filePath, 0o600);
}

export function hasEnvVar(env: EnvFile, key: string): boolean {
  return !!env.values[key] && env.values[key].length > 0;
}

export function maskSecret(value: string): string {
  if (value.length <= 4) return '****';
  return `${'*'.repeat(Math.min(value.length - 4, 20))}${value.slice(-4)}`;
}
